import ollama
from typing import Dict, Any
from app.config import get_settings
from app.utils.logger import logger
import warnings
import json

# Suppress warnings
warnings.filterwarnings('ignore')

settings = get_settings()


class AIService:
    """Service for AI interactions using Ollama"""
    
    def __init__(self):
        self.model = settings.ollama_model
        self.client = ollama.AsyncClient()
    
    async def generate_response(self, prompt: str, context: Dict[str, Any] = None) -> str:
        """
        Generate AI response using Ollama
        """
        try:
            logger.log_thought(f"Constructing optimal search matrix and contextual parameters for query...")
            # Build the full prompt
            full_prompt = self._build_prompt(prompt, context)
            
            logger.log_action("Interrogating local AI models", target=self.model)
            # Call Ollama with streaming enabled
            stream = await self.client.generate(
                model=self.model,
                prompt=full_prompt,
                stream=True,
                options={
                    "temperature": 0.6,
                    "repeat_penalty": 1.15,
                    "top_p": 0.9,
                    "stop": ["End of Report", "Generated by AI"]
                }
            )
            
            full_response = ""
            logger.stream_start()  # Signal frontend: AI tokens incoming
            try:
                async for chunk in stream:
                    token = chunk.get('response', '')
                    if token:
                        full_response += token
                        logger.stream_token(token)
            except Exception as stream_err:
                logger.log_error(f"Stream interrupted: {str(stream_err)}")
            finally:
                logger.stream_end()  # Signal frontend: AI stream finished
            
            logger.log_success("Model response synthesized.")
            return full_response
        
        except Exception as e:
            logger.log_error(f"Core failure during model synthesis: {str(e)}")
            return f"JARVIS encountered an error: {str(e)}"
    
    def _build_prompt(self, query: str, context: Dict[str, Any] = None) -> str:
        """Build comprehensive prompt for AI"""
        
        system_prompt = """You are JARVIS, an Elite Strategic Intelligence Analyst and advanced AI assistant.
 Your analysis is NEVER superficial. You produce DEEP, multi-paragraph intelligence dossiers.
You write like a seasoned intelligence analyst preparing a classified briefing for a high-ranking official.
Every section must be 3-5 detailed paragraphs minimum. Use analytical language ("Data suggests...", "Pattern analysis reveals...", "Cross-referencing indicates...").

CRITICAL IDENTITY CORRELATION RULES:
1. **EXACT MATCH PRIORITY**: You MUST ONLY analyze the specific identity requested: '{query}'.
2. **FAMOUS ENTITY DISCRIMINATION**: If the requested name is similar to a world-famous figure (e.g., 'Yiğit Erdoğan' vs 'Recep Tayyip Erdoğan' OR 'John Smith' vs 'John Smith (Celebrity)'), you MUST check the context for specific differentiators (age, location, job).
3. **HALLUCINATION BLOCK**: If the search context predominantly discusses the famous figure and NOT the specific target, you MUST DISCARD that context. It is better to state 'Insufficient verified intelligence' than to provide a profile of the wrong person.
4. **FALLBACK PROTOCOL**: If traditional biographical data (Wikipedia, News) is missing for the target, but Social Media profiles (GitHub, Twitter, LinkedIn) with bios are present, you MUST prioritize these social bios to build the profile. Social Media bios are the most reliable 'fallback' when a person isn't widely famous.

Format the intelligence dossier using **ALL CAPS BOLD** headers. 

CRITICAL STRUCTURE RULES:
- ONLY include sections where you have ACTUAL VERIFIED DATA or strong analytical hypotheses.
- DO NOT create empty sections. DO NOT use placeholders like `[Your Organization]`, `[Date]`, or `[Contact Information]`.
- If information is scarce, write a single concise summary and STOP GENERATING IMMEDIATELY.
- NEVER generate templates, boilerplate endings, or artificial sign-offs like "End of Report" or "Generated by AI".
- Do NOT repeat the same sentence or paragraph.

Suggested Sections (Use only if relevant data exists):
1. **STRATEGIC BIOGRAPHY**: Life arc, education, career.
2. **PSYCHOLOGICAL PROFILE & PUBLIC PERSONA**: Communication style, leadership, motivations.
3. **DIGITAL FOOTPRINT**: Social media strategy, online influence.
4. **NOTABLE ACHIEVEMENTS**: Significant accomplishments with context.
5. **CONTROVERSIES**: Public issues or polarizing decisions.
6. **FIELD INFLUENCE**: Key allies, connections, industry impact.
7. **COMPARABLE FIGURES**: Direct competitors or peers.

10. **SOCIAL NODES**: Verified links formatted as clickable markdown: `[Platform Name](URL)`.

CRITICAL RULES:
- Write deeply analytical content.
- Do NOT artificially inflate your response or repeat yourself.
- Use ALL available context data to enrich your analysis.
- If limited information, provide a concise summary. DO NOT loop or repeat filler text.
- Do not use placeholders."""
        
        user_prompt = f"\n\nUser Query: {query}"
        user_prompt += f"\n\nCRITICAL RESTRICTION: You MUST ONLY write about the exact requested person: '{query}'. If the search context is about a CLEARLY DIFFERENT person (with a completely different name), you MUST IGNORE that context entirely. Do not invent information. If there is limited or no information about the specific requested person '{query}', simply state: 'Insufficient verified intelligence available for this individual.' Do NOT substitute another similar-sounding person."
        
        if context:
            context_str = "\n\nAvailable Context:"
            
            if context.get('github'):
                context_str += f"\n\nGitHub Profile:\n{context['github']}"
            
            if context.get('web_search'):
                context_str += f"\n\nWeb Search Results:\n{context['web_search']}"
            
            if context.get('social_media'):
                context_str += f"\n\nSocial Media Profiles:\n{context['social_media']}"
            
            if context.get('deep_context'):
                context_str += f"\n\nAdditional Intelligence (Deep Context):\n{context['deep_context']}"
            
            user_prompt += context_str
        
        return system_prompt.replace('{query}', query) + user_prompt
    
    async def extract_profile_data(self, ai_response: str, query: str) -> Dict[str, Any]:
        """
        Extract structured profile data from AI response
        """
        # Ask AI to structure the data
        extraction_prompt = f"""Based on this information about "{query}", 
extract and return ONLY a JSON object with these fields:
- name: string
- description: string (brief summary)
- similar_profiles: array of strings (names of similar people)
- estimated_location: string (guessed country)
- capital_city: string (capital of that country)
- social_media_score: integer (0-100, estimate based on number of linked accounts and recency of posts/activity)
- last_activity_summary: string (brief 2-4 word summary of when they were last active, e.g., "Active today", "Active last week", "No recent activity")
- cross_validation_issues: array of strings (Identify any significant inconsistencies across different data sources. E.g., 'GitHub location is Turkey but LinkedIn says USA' or 'Web results indicate doctor, GitHub indicates programmer'. If all sources match and refer to the same person, return an empty array [])

Previous Information:
{ai_response}

Return ONLY valid JSON, no other text."""
        
        try:
            logger.log_thought("Attempting to parse bio-data and network nodes from unstructured text...")
            response = await self.client.generate(
                model=self.model,
                prompt=extraction_prompt,
                options={
                    "temperature": 0.1,
                    "top_p": 0.1
                }
            )
            
            # Try to parse JSON from response
            import json
            response_text = response['response'].strip()
            
            # Find JSON in response
            start_idx = response_text.find('{')
            end_idx = response_text.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                json_str = response_text[start_idx:end_idx]
                parsed_data = json.loads(json_str)
                logger.log_success("Bio-data nodes successfully extracted.")
                return parsed_data
            
            # Fallback
            logger.log_warning("Failed to locate clean JSON structure. Initiating fallback protocol.")
            return {
                "name": query,
                "description": ai_response[:500],
                "similar_profiles": [],
                "cross_validation_issues": []
            }
        
        except Exception as e:
            logger.log_error(f"Data extraction node failed: {e}")
            return {
                "name": query,
                "description": ai_response[:500] if ai_response else "",
                "similar_profiles": [],
                "cross_validation_issues": []
            }

    async def chat_with_context(self, query_name: str, messages: list):
        """
        RAG Chat generator using stored JSON context.
        Yields tokens for StreamingResponse.
        """
        import os
        import json
        import re
        
        # 1. Load context
        safe_filename = re.sub(r'[^a-zA-Z0-9_\-]', '_', query_name.lower())
        context_path = f"data/contexts/{safe_filename}.json"
        
        context_text = ""
        if os.path.exists(context_path):
            try:
                with open(context_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                if data.get('github'):
                    context_text += "GITHUB PROFILE DATA:\n" + data['github'] + "\n\n"
                if data.get('social_media'):
                    context_text += data['social_media'] + "\n\n"
                
                deep_ctx = data.get('deep_context', '')
                if len(deep_ctx) > 12000:
                    deep_ctx = deep_ctx[:12000] + "... [TRUNCATED DUE TO CONTEXT LIMIT]"
                context_text += "WEB SEARCH DEEP CONTEXT:\n" + deep_ctx
                
            except Exception as e:
                logger.log_warning(f"Failed to load RAG context: {e}")
                context_text = "ERROR: Could not read context file."
        else:
            context_text = "ERROR: No background context found. A deep connection scan might not have been performed yet."

        # 2. Build precision prompt
        system_prompt = f"""You are J.A.R.V.I.S., an advanced AI interacting with the user about a target entity named '{query_name}'.
You must answer the user's questions based EXCLUSIVELY on the gathered intelligence context below.
CRITICAL RULES:
1. DO NOT HALLUCINATE OR GUESS. If the context does not contain the answer, say "I do not have sufficient data in the current intelligence context to answer this."
2. DO NOT USE EXTERNAL KNOWLEDGE. Only use the text provided.
3. Keep answers concise, highly analytical, and direct. Use J.A.R.V.I.S. persona (professional, objective).

=== J.A.R.V.I.S INTELLIGENCE CONTEXT ===
{context_text}
========================================"""
        
        # Format messages for Ollama Chat API
        formatted_messages = [
            {"role": "system", "content": system_prompt}
        ]
        
        # Add user history
        for msg in messages:
            # Handle Pydantic model vs dict
            role = msg.role if hasattr(msg, 'role') else msg['role']
            content = msg.content if hasattr(msg, 'content') else msg['content']
            formatted_messages.append({"role": role, "content": content})
            
        # 3. Stream response
        try:
            response = await self.client.chat(
                model=self.model,
                messages=formatted_messages,
                stream=True,
                options={
                    "temperature": 0.2, # Very low temp to prevent hallucination in facts
                    "top_p": 0.5,
                    "repeat_penalty": 1.1
                }
            )
            
            async for chunk in response:
                if 'message' in chunk and 'content' in chunk['message']:
                    # Yield raw tokens for SSE reading
                    yield chunk['message']['content']
                    
        except Exception as e:
            logger.log_error(f"Chatbot neural link failed: {e}")
            yield f"\n\n[SYSTEM ERROR: Neural reasoning engine failure. Details: {e}]"

    async def analyze_sentiment(self, text_context: str) -> dict:
        """
        Takes raw scraped text and performs a psychological/sentiment analysis using Ollama.
        Returns a specific JSON structure with pos/neu/neg percentages and dominant emotion.
        """
        if not text_context or len(text_context.strip()) < 50:
            return {
                "positive": 33,
                "neutral": 34,
                "negative": 33,
                "dominant_emotion": "INSUFFICIENT DATA",
                "summary": "Veri yetersiz."
            }
            
        # Protect context window limit
        if len(text_context) > 10000:
            text_context = text_context[:10000]

        sentiment_prompt = f"""You are J.A.R.V.I.S., analyzing the psychological profile and public sentiment of an entity based on the following scraped text data.
Analyze the overall tone, sentiment, and emotion present in the text.
You MUST respond IN TURKISH.
You MUST output ONLY a valid JSON object without any markdown formatting or extra text.

Required JSON Structure:
{{
  "positive": <integer 0-100 representing positive sentiment percentage>,
  "neutral": <integer 0-100 representing neutral sentiment percentage>,
  "negative": <integer 0-100 representing negative sentiment percentage>,
  "dominant_emotion": "<string, one or two words describing the main emotion, e.g., 'Öfkeli', 'Profesyonel', 'Neşeli', 'Agresif'>",
  "summary": "<string, 1 short sentence summarizing the public perception>"
}}

CRITICAL: The sum of positive + neutral + negative MUST exactly equal 100.
Do NOT include ```json tags.

TEXT TO ANALYZE:
{text_context}
"""
        
        try:
            response = await self.client.generate(
                model=self.model,
                prompt=sentiment_prompt,
                options={
                    "temperature": 0.1,
                    "top_p": 0.1
                }
            )
            
            response_text = response['response'].strip()
            
            # Extract JSON
            start_idx = response_text.find('{')
            end_idx = response_text.rfind('}') + 1
            
            if start_idx != -1 and end_idx > start_idx:
                import json
                json_str = response_text[start_idx:end_idx]
                parsed_data = json.loads(json_str)
                
                # Sanity check percentages
                pos = int(parsed_data.get('positive', 33))
                neu = int(parsed_data.get('neutral', 34))
                neg = int(parsed_data.get('negative', 33))
                
                total = pos + neu + neg
                if total == 0:
                    pos, neu, neg = 33, 34, 33
                elif total != 100:
                    # Normalize
                    pos = int((pos / total) * 100)
                    neu = int((neu / total) * 100)
                    neg = 100 - (pos + neu)
                    
                return {
                    "positive": pos,
                    "neutral": neu,
                    "negative": neg,
                    "dominant_emotion": parsed_data.get('dominant_emotion', 'Belirsiz').upper(),
                    "summary": parsed_data.get('summary', 'Analiz tamamlanamadı.')
                }
                
        except Exception as e:
            logger.log_error(f"Sentiment analysis matrix failure: {e}")
            
        return {
            "positive": 33,
            "neutral": 34,
            "negative": 33,
            "dominant_emotion": "ERROR",
            "summary": "Analiz modülü çöktü."
        }
