"""initial_schema

Revision ID: 25fb8c4668db
Revises: 
Create Date: 2026-03-19 15:14:46.361767
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fb8c4668db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('snapchat_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tumblr_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pinterest_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medium_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('threads_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('steam_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tinder_mention', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bumble_mention', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discord_mention', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_numbers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cross_validation_issues', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('network_connections', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('network_connections')
        batch_op.drop_column('cross_validation_issues')
        batch_op.drop_column('phone_numbers')
        batch_op.drop_column('discord_mention')
        batch_op.drop_column('bumble_mention')
        batch_op.drop_column('tinder_mention')
        batch_op.drop_column('steam_url')
        batch_op.drop_column('threads_url')
        batch_op.drop_column('medium_url')
        batch_op.drop_column('pinterest_url')
        batch_op.drop_column('tumblr_url')
        batch_op.drop_column('snapchat_url')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('spotify_url')

    # ### end Alembic commands ###
